### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by jtrechot** [kyegomez/LongNet#12]
Hello, 

Thank you for the great effort to provide a version of LongNet!  😃 
I noticed that I have some import issues, for example in the `LongNet/model.py` file:

```
ModuleNotFoundError: No module named 'LongNet.transformer'
```

I think this is due to some modification of the imports that used to be `from LongNet.Transformer import LongNet` but was changed to `from LongNet.transformer import LongNet`

Would it be possible to have a check on that  ? 🔧

Thank you!

**Comment by kyegomez** [comment]
@jtrechot Hey please excuse me for the issue, I've fixed it now. We're still working on the model architecture to get it ready for training and democratization.
