### ISSUE TITLE
where to find any experiments on real dataset？

### ISSUE THREAD

**Issue by decoda-huanyi** [kyegomez/LongNet#15]
Where can I find some examples showing how to train longnet on a real dataset?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LongNet/issues/15">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LongNet/issues/15/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LongNet/issues/15/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@decoda-huanyi Hey I'm still working on the actual model architecture, i need help with implementing it. 

Would you like to help integrate it

**Comment by xiehuanyi** [comment]
I am acturally interested. Which dataset shall we start with? In my opinion, this dataset should have very long samples so that we can demostrate the power of longnet. I am not sure. Could we just try it on a noval or, you know, some other modals like music or images?

**Comment by kyegomez** [comment]
@xiehuanyi Hey we're about to start training on the enwiki dataset there's a competition for some money on whoever can train the best model on 1gb of wikipedia data!
