### ISSUE TITLE
ModuleNotFoundError: No module named 'LongNet'

### ISSUE THREAD

**Issue by copi143** [kyegomez/LongNet#16]
**Issue Description:**

I encountered an issue while using the `pip install LongNet` command to install the LongNet package. When attempting to import a module using `from LongNet.attention import DilatedAttention`, I received the following error:
```
ModuleNotFoundError: No module named 'LongNet'
```
Upon investigating the installation directory of pip packages (`/usr/local/lib/python3.11/dist-packages`), I noticed that the actual installation directory for the LongNet library was named as `longnet` (all lowercase).

**Suggested Resolution:**

It appears that there might be a mismatch between the library's name and the installation directory. To resolve this issue, one of the following actions could be taken:

1. Rename the Installation Directory:
   Rename the installation directory from `longnet` to `LongNet` to match the capitalization of the library's name. This would align the installation directory with the expected import statement.

2. Adjust Import Statements:
   Modify the import statements within the library's codebase to use lowercase import paths, matching the installation directory. For example, change `from LongNet.attention import DilatedAttention` to `from longnet.attention import DilatedAttention`.

*This was generated by ChatGPT based on my description.*

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LongNet/issues/16">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LongNet/issues/16/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LongNet/issues/16/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@copi143 Hey should be fixed now!
