### ISSUE TITLE
LongNet can be used for fine-tuning large language models?

### ISSUE THREAD

**Issue by mahuixian** [kyegomez/LongNet#17]
If I want to use LongNet to fine-tune the already trained large language model, can it be implemented？

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LongNet/issues/17">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LongNet/issues/17/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LongNet/issues/17/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@mahuixian Add the masking strategy into the existing model's attention!
