### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Qembo154** [kyegomez/LongNet#19]
Non-A100 GPU detected, using math or mem efficient attention if input tensor is on cuda
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-3-9b5725f01303>](https://localhost:8080/#) in <cell line: 22>()
     20 #create model and data
     21 model = DilatedAttention(d_model, num_heads, dilation_rate, segment_size).to(device)
---> 22 x = torch.randn((batch_size, seq_len, d_model), device=device, dtype=dtype)
     23 
     24 

OutOfMemoryError: CUDA out of memory. Tried to allocate 305.18 GiB (GPU 0; 14.75 GiB total capacity; 16.00 KiB already allocated; 14.09 GiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LongNet/issues/19">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LongNet/issues/19/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LongNet/issues/19/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@Qembo154 Hey you're gpu is out of memory. Try again
