### ISSUE TITLE
Basemodel usage

### ISSUE THREAD

**Issue by PriNova** [kyegomez/LongNet#2]
Hey kyegomez,

I'm interested in trying out the implementation.
Is it already possible to use a basemodel for this?

**Comment by kyegomez** [comment]
Hey @PriNova yes, I am working on this now with the torchscale repository! 

https://github.com/kyegomez/LongNet/blob/main/LongNet/torchscale/torchscale/architecture/decoder.py

I need help integrating it and providing usage examples!

**Comment by kyegomez** [comment]
@PriNova I implemented the model architecture and a training script here:

https://github.com/kyegomez/LongNet/blob/0.0.3/LongNet/model.py
