### ISSUE TITLE
KeyError: 'module.token_embs.0.gamma'

### ISSUE THREAD

**Issue by pokameng** [kyegomez/LongNet#9]
@kyegomez 
hello bro!!
Thanks for your code
When i run training.py , something is wrong:
`File "LongNet/training.py", line 364, in decoupled_optimizer
    no_decay_param.append(param_dict[param])
KeyError: 'module.token_embs.0.gamma'`

**Comment by kyegomez** [comment]
@pokameng Hey 👋 Thank you for being a Human 😊  


And, yeah we're still working on the model and the training script! It'll be done soon!
